name: Build docker image

on:
  push:
    branches:
      - main

  workflow_dispatch:

defaults:
  run:
    working-directory: ./

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["app"]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Build and push the image
        run: |
          IMAGE_ID=${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.image }}

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's/[\/-]/_/g')
          TAG=$IMAGE_ID:$VERSION
          # Change all uppercase to lowercase
          TAG=$(echo $TAG | tr '[A-Z]' '[a-z]')
          echo TAG=$TAG

          docker build . -f ${{ matrix.image }}.dockerfile -t $TAG
          docker push $TAG
